version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - "8080:8080"  # Jenkins chạy trên cổng 8080
      - "50000:50000" # Cổng để Jenkins agent kết nối
    container_name: jenkins-container
    volumes:
      - /home/phuc/jenkins_compose/jenkins_configuration:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - app-network

  fastapi-app:
    build:
      context: ./  # Đảm bảo Dockerfile của FastAPI nằm trong thư mục hiện tại
    ports:
      - "8081:8081"  # FastAPI chạy trên cổng 8081
    volumes:
      - .:/app  # Mount mã nguồn vào container
    container_name: fastapi-app-container
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
